spring:
  application:
    name: hospital-chatbot
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hospital_chatbot?useSSL=false&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    com.banda.hospital chatbot: DEBUG

server:
    port: 8080

